from pathlib import Path

import nbformat as nbf


def generate_notebook(

    dataset_path,

    target,

    model_path,

    schema_report,

    phase5_report_path,

    explainability_path,

    output_path=
        "artifacts/phase6/AutoDS_Analysis.ipynb"
):

    output_path = Path(
        output_path
    )


    output_path.parent.mkdir(

        parents=True,

        exist_ok=True
    )


    notebook = nbf.v4.new_notebook()


    cells = []


    cells.append(

        nbf.v4.new_markdown_cell(
            """
# Autonomous Data Scientist - Final Analysis

This notebook was automatically generated by AutoDS.

It provides access to:

- Processed dataset
- Final champion model
- Verified Phase 5 results
- Explainability artifacts
- Example predictions
"""
        )
    )


    cells.append(

        nbf.v4.new_code_cell(
            """
import json
import joblib
import pandas as pd
"""
        )
    )


    cells.append(

        nbf.v4.new_code_cell(
            f"""
DATASET = r"{dataset_path}"
TARGET = r"{target}"
MODEL_PATH = r"{model_path}"
PHASE5_REPORT = r"{phase5_report_path}"
SHAP_IMPORTANCE = r"{explainability_path}"
"""
        )
    )


    cells.append(

        nbf.v4.new_code_cell(
            """
df = pd.read_csv(DATASET)

print("Dataset shape:", df.shape)

df.head()
"""
        )
    )


    cells.append(

        nbf.v4.new_code_cell(
            """
with open(PHASE5_REPORT, "r", encoding="utf-8") as file:
    phase5_report = json.load(file)

phase5_report
"""
        )
    )


    cells.append(

        nbf.v4.new_code_cell(
            """
model = joblib.load(MODEL_PATH)

model
"""
        )
    )


    excluded = (
        schema_report.get(
            "excluded_columns",
            []
        )
    )


    cells.append(

        nbf.v4.new_code_cell(
            f"""
excluded_columns = {repr(excluded)}

X = df.drop(
    columns=[TARGET] + excluded_columns,
    errors="ignore"
)

sample = X.head(10)

predictions = model.predict(sample)

prediction_table = sample.copy()
prediction_table["AutoDS_Prediction"] = predictions

prediction_table
"""
        )
    )


    cells.append(

        nbf.v4.new_code_cell(
            """
try:
    shap_importance = pd.read_csv(SHAP_IMPORTANCE)
    shap_importance.head(20)
except Exception as error:
    print("SHAP importance unavailable:", error)
"""
        )
    )


    notebook[
        "cells"
    ] = cells


    with open(

        output_path,

        "w",

        encoding="utf-8"

    ) as file:

        nbf.write(
            notebook,
            file
        )


    return str(
        output_path
    )